=== Q-177/Test/Test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
	<element name="teaching-test">
		<complexType>
			<sequence>
				<element name="commoditly" minOccurs="1" maxOccurs="9999">
					<complexType>
						<sequence>
							<element name="commoditly-name" type="string"></element>
							<element name="price" type="integer"></element>
							<element name="mode-of-payment" type="string"></element>
						</sequence>
						<attribute name="no" type="integer" use="required"></attribute>
					</complexType>
				</element>
			</sequence>
		</complexType>
</element>
</schema>

=== Q-177/Test/Test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--教学计划-->
<teaching-test xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Test.xsd">
    <commoditly no="1">
        <commoditly-name>晾衣架</commoditly-name>
        <price>188</price>
        <mode-of-payment>微信支付</mode-of-payment>
    </commoditly>
    <commoditly no="2">
        <commoditly-name>落地空调</commoditly-name>
        <price>2999</price>
        <mode-of-payment>支付宝支付</mode-of-payment>
    </commoditly>
    <commoditly no="3">
        <commoditly-name>迷你沙发</commoditly-name>
        <price>999</price>
        <mode-of-payment>现金支付</mode-of-payment>
    </commoditly>
</teaching-test>
